In [16]:
from warnings import filterwarnings
filterwarnings("ignore")

#### Business Usecases:- Build a model that predicts the speices of Iris flowers based on sepal length,sepal width,petal width and petal length

In [17]:
###### Step-1 Data Gathering
path=r"https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/iris.csv"
import pandas as pd
df=pd.read_csv(path)
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [18]:
df.shape

(150, 5)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [20]:
X= df.drop(columns=["species"])
y=df["species"]

In [21]:
X.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [22]:
y.head()

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

In [23]:
#Feature Engineering: Data cleaning and data preprocessing

from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
pipeline= make_pipeline(SimpleImputer(strategy="mean"),
                        StandardScaler()
                        ).set_output(transform="pandas")
pipeline

Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('standardscaler', StandardScaler())])

In [24]:
x_pipeline=pipeline.fit_transform(X)
display(x_pipeline.head())
display(X.head())

   sepal_length  sepal_width  petal_length  petal_width
0     -0.900681     1.019004     -1.340227    -1.315444
1     -1.143017    -0.131979     -1.340227    -1.315444
2     -1.385353     0.328414     -1.397064    -1.315444
3     -1.506521     0.098217     -1.283389    -1.315444
4     -1.021849     1.249201     -1.340227    -1.315444

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [25]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_pipeline,y)

LogisticRegression()

In [26]:
model.score(x_pipeline,y)

0.9733333333333334

In [35]:
from sklearn.metrics import f1_score,classification_report,confusion_matrix
ypred=model.predict(x_pipeline)
f1 = f1_score(y, ypred, average="weighted")
class_report = classification_report(y, ypred)
conf_matrix = confusion_matrix(y, ypred)

In [39]:
print(class_report)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        50
  versicolor       0.98      0.94      0.96        50
   virginica       0.94      0.98      0.96        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97       150

In [41]:
import joblib
joblib.dump(model,"model.joblib")
joblib.dump(pipeline,"pipeline.joblib")

['pipeline.joblib']

In [42]:
path2="https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/iris_sample.csv"
xnew=pd.read_csv(path2)
xnew.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.5          2.5           4.0          1.3
1           6.9          3.1           5.1          2.3
2           5.1          2.5           3.0          1.1
3           4.4          2.9           NaN          0.2
4           5.9          3.0           5.1          1.8

In [44]:
pre_loaded_pipeline=joblib.load("pipeline.joblib")
model_loaded=joblib.load("model.joblib")

In [51]:
pre_loaded_pipeline

Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('standardscaler', StandardScaler())])

In [52]:
model_loaded

LogisticRegression()

In [53]:
xnew_pre = pre_loaded_pipeline.transform(xnew)
xnew_pre

    sepal_length  sepal_width  petal_length  petal_width
0      -0.416010    -1.282963      0.137547     0.132510
1       1.280340     0.098217      0.762758     1.448832
2      -0.900681    -1.282963     -0.430828    -0.130755
3      -1.748856    -0.362176      0.000000    -1.315444
4       0.068662    -0.131979      0.762758     0.790671
5      -0.416010     1.019004     -1.397064    -1.315444
6      -0.294842     0.000000     -0.089803     0.132510
7       0.795669    -0.131979      0.819596     1.053935
8      -0.658345     1.479398     -1.283389    -1.315444
9      -0.900681     0.788808     -1.283389     0.000000
10      0.310998    -0.592373      0.137547     0.132510
11     -0.416010    -1.513160     -0.032966    -0.262387
12      2.249683    -0.131979      1.331133     1.448832
13      1.280340     0.098217      0.649083     0.395774
14      0.189830    -1.973554      0.705921     0.395774

In [54]:
preds=model_loaded.predict(xnew_pre)
preds

array(['versicolor', 'virginica', 'versicolor', 'setosa', 'virginica',
       'setosa', 'versicolor', 'virginica', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'virginica', 'versicolor', 'virginica'],
      dtype=object)

In [59]:
xnew['Species_predictions'] = preds
xnew

    sepal_length  sepal_width  petal_length  petal_width Species_predictions
0            5.5          2.5           4.0          1.3          versicolor
1            6.9          3.1           5.1          2.3           virginica
2            5.1          2.5           3.0          1.1          versicolor
3            4.4          2.9           NaN          0.2              setosa
4            5.9          3.0           5.1          1.8           virginica
5            5.5          3.5           1.3          0.2              setosa
6            5.6          NaN           3.6          1.3          versicolor
7            6.5          3.0           5.2          2.0           virginica
8            5.3          3.7           1.5          0.2              setosa
9            5.1          3.4           1.5          NaN              setosa
10           6.1          2.8           4.0          1.3          versicolor
11           5.5          2.4           3.7          1.0          versicolor
12           7.7          3.0           6.1          2.3           virginica
13           6.9          3.1           4.9          1.5          versicolor
14           6.0          2.2           5.0          1.5           virginica

In [60]:
xnew.to_csv("iris_predictions.csv",index=False)

In [61]:
xnew

    sepal_length  sepal_width  petal_length  petal_width Species_predictions
0            5.5          2.5           4.0          1.3          versicolor
1            6.9          3.1           5.1          2.3           virginica
2            5.1          2.5           3.0          1.1          versicolor
3            4.4          2.9           NaN          0.2              setosa
4            5.9          3.0           5.1          1.8           virginica
5            5.5          3.5           1.3          0.2              setosa
6            5.6          NaN           3.6          1.3          versicolor
7            6.5          3.0           5.2          2.0           virginica
8            5.3          3.7           1.5          0.2              setosa
9            5.1          3.4           1.5          NaN              setosa
10           6.1          2.8           4.0          1.3          versicolor
11           5.5          2.4           3.7          1.0          versicolor
12           7.7          3.0           6.1          2.3           virginica
13           6.9          3.1           4.9          1.5          versicolor
14           6.0          2.2           5.0          1.5           virginica